Repository cfpb/capital-framework, pull requests merged in 2019-03, with the labels that each got.

#893 Fix lerna-changelog command
  scripts/generate-changelog.sh
Labels: internal

#892 cf-notifications: Update links documentation
  packages/cf-notifications/usage.md
Labels: documentation

#897 Convert hardcoded values to use grid_gutter-width variable.
  packages/cf-layout/src/cf-layout.less
Labels: bug

#901 Improve the changelog's layout, clarify release steps
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  scripts/generate-changelog.sh
Labels: internal
