Repository cfpb/capital-framework, pull requests merged in 2019-05, with the labels that each got.

#920 Delete some unneded things, move parseComponentName to utils
  config/environment.js
  scripts/gulp/scripts.js
  scripts/gulp/styles.js
  scripts/gulp/test.js
  scripts/templates/CHANGELOG.legacy.md
  scripts/templates/preview.html.tmpl
  scripts/utils/parseComponentName.js
Labels: internal

#921 cf-notifications: Target only notification icon
  docs/_includes/usage/cf-notifications/usage.md
  docs/dist/css/main.css
  packages/cf-notifications/src/molecules/notification.less
  packages/cf-notifications/usage.md
Labels: bug

#922 Remove git step from changelog generation
  CONTRIBUTING.md
  scripts/generate-changelog.sh
Labels: internal

#923 Rename temporary changelog file
  scripts/generate-changelog.sh
Labels: internal

#924 Fix lerna-changelog typo
  scripts/generate-changelog.sh
Labels: internal

#925 Remove expandables test cruft
  test/unit-test/src/cf-expandables/src/Expandable-spec.js
Labels: bug

#926 Properly space expandables' comments
  packages/cf-expandables/src/cf-expandables.less
Labels: documentation

#927 Update lerna dependency
  npm-packages-offline-cache/@lerna-add-3.14.0.tgz
  npm-packages-offline-cache/@lerna-batch-packages-3.14.0.tgz
  npm-packages-offline-cache/@lerna-bootstrap-3.14.0.tgz
  npm-packages-offline-cache/@lerna-changed-3.14.1.tgz
  npm-packages-offline-cache/@lerna-check-working-tree-3.14.1.tgz
  npm-packages-offline-cache/@lerna-clean-3.14.0.tgz
  npm-packages-offline-cache/@lerna-collect-uncommitted-3.14.1.tgz
  npm-packages-offline-cache/@lerna-collect-updates-3.14.0.tgz
  npm-packages-offline-cache/@lerna-command-3.14.0.tgz
  npm-packages-offline-cache/@lerna-conventional-commits-3.14.0.tgz
  npm-packages-offline-cache/@lerna-create-3.14.0.tgz
  npm-packages-offline-cache/@lerna-create-symlink-3.14.0.tgz
  npm-packages-offline-cache/@lerna-diff-3.14.0.tgz
  npm-packages-offline-cache/@lerna-exec-3.14.0.tgz
  npm-packages-offline-cache/@lerna-filter-options-3.14.0.tgz
  npm-packages-offline-cache/@lerna-import-3.14.0.tgz
  npm-packages-offline-cache/@lerna-init-3.14.0.tgz
  npm-packages-offline-cache/@lerna-link-3.14.0.tgz
  npm-packages-offline-cache/@lerna-list-3.14.0.tgz
  npm-packages-offline-cache/@lerna-listable-3.14.0.tgz
  npm-packages-offline-cache/@lerna-npm-dist-tag-3.14.0.tgz
  npm-packages-offline-cache/@lerna-npm-publish-3.14.0.tgz
  npm-packages-offline-cache/@lerna-otplease-3.14.0.tgz
  npm-packages-offline-cache/@lerna-pack-directory-3.14.0.tgz
  npm-packages-offline-cache/@lerna-package-graph-3.14.0.tgz
  npm-packages-offline-cache/@lerna-prerelease-id-from-version-3.14.0.tgz
  npm-packages-offline-cache/@lerna-publish-3.14.1.tgz
  npm-packages-offline-cache/@lerna-query-graph-3.14.0.tgz
  npm-packages-offline-cache/@lerna-run-3.14.0.tgz
  npm-packages-offline-cache/@lerna-run-lifecycle-3.14.0.tgz
  npm-packages-offline-cache/@lerna-run-topologically-3.14.0.tgz
  npm-packages-offline-cache/@lerna-symlink-binary-3.14.0.tgz
  npm-packages-offline-cache/@lerna-symlink-dependencies-3.14.0.tgz
  npm-packages-offline-cache/@lerna-version-3.14.1.tgz
  npm-packages-offline-cache/eventemitter3-3.1.2.tgz
  npm-packages-offline-cache/lerna-3.14.1.tgz
  npm-packages-offline-cache/node-gyp-4.0.0.tgz
  npm-packages-offline-cache/npm-lifecycle-2.1.1.tgz
  npm-packages-offline-cache/p-queue-4.0.0.tgz
  package.json
  yarn.lock
Labels: internal

#906 Removed the deprecated font-icon system from cf-icons
  packages/cf-buttons/usage.md
  packages/cf-icons/src/cf-icons.less
  packages/cf-icons/src/fonts/cf-icons.eot
  packages/cf-icons/src/fonts/cf-icons.svg
  packages/cf-icons/src/fonts/cf-icons.ttf
  packages/cf-icons/src/fonts/cf-icons.woff
  packages/cf-icons/usage.md
Labels: breaking
