Repository cfpb/capital-framework, pull requests merged in 2019-06, with the labels that each got.

#930 Update Featured Content Module styling
  docs/_includes/usage/cf-core/usage.md
  docs/_includes/usage/cf-layout/usage.md
  docs/dist/css/main.css
  packages/cf-core/usage.md
  packages/cf-layout/src/cf-layout.less
  packages/cf-layout/src/organisms/featured-content-module.less
  packages/cf-layout/usage.md
Labels: bug

#934 cf-forms: Fix issue where path to icons was hardcoded
  docs/src/css/main.less
  packages/cf-forms/src/atoms/select.less
  packages/cf-forms/src/cf-forms.less
  packages/cf-forms/src/molecules/form-fields.less
Labels: bug

#937 Minor formatting and code comment fixes
  docs/dist/css/main.css
  packages/cf-buttons/src/atoms/buttons-with-icons.less
  packages/cf-grid/src/cf-grid.less
  packages/cf-pagination/src/cf-pagination.less
  packages/cf-tables/src/cf-tables.less
  packages/cf-typography/src/atoms/date.less
  packages/cf-typography/src/cf-typography.less
  packages/cf-typography/src/molecules/list.less
  packages/cf-typography/src/molecules/pull-quote.less
Labels: internal

#939 Update download source links
  docs/_includes/hero.html
Labels: internal

#941 Add design system deprecation notice
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  docs/_includes/content-header.html
Labels: internal

#932 cf-forms: Organize docs
  docs/_includes/usage/cf-forms/usage.md
  packages/cf-forms/usage.md
Labels: documentation

#936 cf-forms: Remove reference to CFPB Minicons font
  docs/dist/css/main.css
  packages/cf-forms/src/molecules/form-fields.less
Labels: bug

#943 Add -10 level colors to palette and use in notification backgrounds
  docs/_includes/usage/cf-notifications/usage.md
  docs/dist/css/main.css
  packages/cf-core/src/cf-brand-colors.less
  packages/cf-notifications/src/cf-notifications.less
  packages/cf-notifications/usage.md
Labels: bug

#931 cf-layout: Fix issues in docs
  docs/_includes/usage/cf-buttons/usage.md
  docs/_includes/usage/cf-expandables/usage.md
  docs/_includes/usage/cf-forms/usage.md
  docs/_includes/usage/cf-layout/usage.md
  docs/_includes/usage/cf-pagination/usage.md
  docs/_includes/usage/cf-tables/usage.md
  docs/_includes/usage/cf-typography/usage.md
  packages/cf-buttons/usage.md
  packages/cf-expandables/usage.md
  packages/cf-forms/usage.md
  packages/cf-layout/usage.md
  packages/cf-pagination/usage.md
  packages/cf-tables/usage.md
  packages/cf-typography/usage.md
Labels: documentation
